version: '3.7'


services:
  notebook:
    
    #network_mode: host
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - './docker/mounts/notebooks:/home/jovyan/notebooks'
      - './docker/mounts/videos:/home/jovyan/videos'
      - './vrd:/home/jovyan/notebooks/vrd'
    command: "start-notebook.sh"
    environment:
      - LOGURU_LEVEL=INFO
    networks:
      - vrd-network

networks:
  vrd-network:
